### PR TITLE
Added some of my projects

### PR DESCRIPTION
**Pull request by Gcat101**
Added:
- [Wfetch](https://github.com/gcat101/wfetch)
- [Tui-shop](https://github.com/gcat101/tui-shop)

### CODE REVIEW

**Comment by talwat** [comment]
Hi! This looks good, but your not supposed to specify absolute paths for the config & bin fields.

**Comment by talwat** [comment]
I can fix it later in my spare time :)

**Comment by talwat** [comment]
Also, if you could make a commit to your repos making all the files locally that would be great since IndiePKG should only install to the user's home directory.

**Comment by Gcat101** [comment]
Sorry, all of my projects are based on global paths

**Comment by talwat** [comment]
I'm going to close this because your projects have fixed paths, but feel free to reopen this issue if you update your programs to have local paths or configurable paths.

**Pull request closed without merging**
