### PR TITLE
Improved info and search

### PR DESCRIPTION
**Pull request by lxgr-linux**
Now information for multiple packages at once can be given out.
Search now checks for multiple terms in package names.

### CODE REVIEW

**Comment by talwat** [comment]
Please commit to the **main** branch :)

**Comment by lxgr-linux** [comment]
Done

**Comment by lxgr-linux** [comment]
> Please commit to the **main** branch :)

Hello, I resolved all mergeconflicts with the main branch.

**Comment by lxgr-linux** [comment]
The checks seam to fail, because of rate limiting.

**Comment by talwat** [comment]
I'm probably going to close this because I don't see much use in querying multiple things at once.

**Pull request closed without merging**
